# Generated by Django 5.2.5 on 2025-08-15 08:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อแผนก")),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="รหัสแผนก"
                    ),
                ),
            ],
            options={
                "verbose_name": "แผนก",
                "verbose_name_plural": "แผนก",
            },
        ),
        migrations.CreateModel(
            name="PrintJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=200, verbose_name="ชื่องาน")),
                ("description", models.TextField(blank=True, verbose_name="รายละเอียด")),
                ("requestor", models.CharField(max_length=100, verbose_name="ผู้ขอ")),
                (
                    "date_requested",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="วันที่ขอ"
                    ),
                ),
                ("date_needed", models.DateField(verbose_name="วันที่ต้องการ")),
                (
                    "date_started",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่เริ่มพิมพ์"
                    ),
                ),
                (
                    "date_completed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่เสร็จสิ้น"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "รอดำเนินการ"),
                            ("printing", "กำลังพิมพ์"),
                            ("completed", "เสร็จสิ้น"),
                            ("cancelled", "ยกเลิก"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "ต่ำ"),
                            ("normal", "ปกติ"),
                            ("high", "สูง"),
                            ("urgent", "เร่งด่วน"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="ลำดับความสำคัญ",
                    ),
                ),
                (
                    "print_time_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="เวลาพิมพ์ (ชั่วโมง)"
                    ),
                ),
                (
                    "material_weight_grams",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="น้ำหนักวัสดุ (กรัม)"
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        default="PLA", max_length=50, verbose_name="ชนิดวัสดุ"
                    ),
                ),
                (
                    "material_cost_per_gram",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        max_digits=6,
                        verbose_name="ราคาวัสดุต่อกรัม",
                    ),
                ),
                (
                    "electricity_cost_per_hour",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=6,
                        verbose_name="ค่าไฟต่อชั่วโมง",
                    ),
                ),
                (
                    "labor_cost_per_hour",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        max_digits=6,
                        verbose_name="ค่าแรงต่อชั่วโมง",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="ต้นทุนรวม",
                    ),
                ),
                (
                    "file_upload",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="print_jobs/",
                        verbose_name="ไฟล์ STL/3MF",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.department",
                        verbose_name="แผนก",
                    ),
                ),
            ],
            options={
                "verbose_name": "งานพิมพ์ 3D",
                "verbose_name_plural": "งานพิมพ์ 3D",
                "ordering": ["-priority", "date_needed", "date_requested"],
            },
        ),
    ]
